language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly

addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - cmake
      - gcc
      - binutils-dev
      - libiberty-dev
after_success: |
  if [[ "$TRAVIS_RUST_VERSION" == "stable" ]]; then
  RUSTFLAGS="--cfg procmacro2_semver_exempt" cargo install -f cargo-tarpaulin
  cargo tarpaulin --features="alpn,tls,rust-tls" --out Xml --no-count
  bash <(curl -s https://codecov.io/bash)
  echo "Uploaded code coverage"
  fi
