[package]
name = "actix-web-requestid"
description = "Request ID middleware for actix-web"
version = "0.1.0"
authors = ["Pierre-Alexandre St-Jean <pa@stjean.me>"]
license = "MIT/Apache-2.0"
readme = "README.md"
repository = "https://github.com/pastjean/actix-web-requestid"
homepage = "https://github.com/pastjean/actix-web-requestid"
keywords = ["actix", "actix-web", "web", "middleware", "requestid"]

[dependencies]
actix-web = "0.7.3"
rand = "0.5.5"
